### ISSUE TITLE
[Listing Error] OctoPrint Display Panel

### ISSUE THREAD

**Issue by Hairyloon** [OctoPrint/plugins.octoprint.org#720] opened 2020-12-18 16:48 UTC
The link appears to be broken...

**Which Plugin? (URL to plugin page on plugin repository)**

**What's wrong with the plugin *listing*?**

**Comment by cp2004** [comment] 2020-12-18 16:54
'The Link'

You expect us to search through and test each individual link, or maybe tell us?

Either way, please check this is not a duplicate of #717 first.

**Comment by Hairyloon** [comment] 2020-12-18 16:57
The link to the damned installation.
And if you've had it reported and closed the issue, how come you've not fixed it? It's not bleedin' rocket surgery.

**Comment by cp2004** [comment] 2020-12-18 16:59
Excuse me, but that is not how you respond to someone **unpaid** who **volunteers their time** to fix things for the community.

Have a good day.

**Closed by cp2004** 2020-12-18 16:59 UTC
Labels: listing error, needs review

**Comment by Hairyloon** [comment] 2020-12-18 17:17
> 
> 
> Excuse me, but that is not how you respond to someone **unpaid** who **volunteers their time** to fix things for the community.
> 
> Have a good day.

You started it friend.
Give a bad attitude and you can expect to get one in reply.

**Comment by cp2004** [comment] 2020-12-18 17:24
Given I thought I had fixed the links 8 hours ago, if you were to be specific then it would really help. Because I did go and have a look after commenting to see if I could find one, and I couldn't find one - so my point still stands.

 If you'd come back and said, "this link right here, `brokenlink.com`" and it was one I thought I had already fixed, maybe there was a mistake. Or if it was the same one, I might have told you how you could refresh the repository to make sure nothing was cached. Come on, it is not much to ask to save me some time and say exactly what the problem is, rather than send me off on a wild goose chase trying to find a random broken link somewhere on the plugin repository.

**Comment by Hairyloon** [comment] 2020-12-18 17:49
Given that the entire purpose of that page is to direct people to the software, "**The** link" clearly refers to the link to the software.
Had it been a random link, then I would have said so.

**Comment by foosel** [comment] 2020-12-18 17:56
@Hairyloon your aggressive outburst here is unacceptable, regardless of the issue at hand. Treat people like you would like to be treated.
