### ISSUE TITLE
[Suspicious Plugin Activity] Octoprint-Chituboard

### ISSUE THREAD

**Issue by marndra** [OctoPrint/plugins.octoprint.org#945] opened 2021-09-24 10:37 UTC
### Which Plugin?

https://plugins.octoprint.org/plugins/Chituboard/

### What kind of suspicious activity are you reporting?

something else (specify below)

### If you selected "something else" above, what other kind of suspicious activity did you observe?

installed Octoprint-Chituboard v0.1.3 on my ubuntu 20.04.3 odroid C2 and now octoprint 1.70rc3 can no more boot (instane 1)

### Link to a ticket on the plugin's issue tracker about the problem

https://github.com/OctoPrint/plugins.octoprint.org/issues/944

### Further information you want to provide

I have:
Hardware: Odroid C2 (64GB eccm)
Software: OS ubuntu from hardkernel, updated latest to 20.04.3
Octoprint with 2 virtual instances: first with 1.70rc3 for my tronxy xy3 and second instance geeetech i3pro (octo 1.6)
Instance 2 / Printer: geeetech i3pro with marlin
Instance 1 / printer: tronxy xy3 with chitu 2.0

Everything worked fine until I installed und octoprint instance for tronxy printer via plugin manager the chituboard.
Now the octorpint cannt connect to my configured instance 192.168.1.45:5001
The other worked fine, sure the chite plugin is not needed there (marlin)

How can I uninstall (via SSH) this Chitu plugin???

regards Martin

**Comment by cp2004** [comment] 2021-09-24 11:51
Duplicate of #944

This is not suspicious activity, please don't post duplicate issues.

**Closed by cp2004** 2021-09-24 11:51 UTC
Labels: needs review, suspicious plugin activity
