### ISSUE TITLE
[Listing Error] OctoPrint-TuyaSmartplug

### ISSUE THREAD

**Issue by justin5188** [OctoPrint/plugins.octoprint.org#552] opened 2020-07-14 02:28 UTC
https://github.com/ziirish/OctoPrint-TuyaSmartplug

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-DPtYRo/pytuya/

**Comment by jneilliii** [comment] 2020-07-14 02:30
Appears you've already opened an issue on the plugin's repository, closing as the issue is with that plugin.

**Closed by jneilliii** 2020-07-14 02:30 UTC
